(()=>{'use strict';
const $=id=>document.getElementById(id), canvas=$('canvas'), ctx=canvas.getContext('2d'), onion=$('onion'), ox=onion.getContext('2d');
const W=640,H=480,KEY='frameforge-go-v2',THEME='frameforge-go-theme';let frames=[],current=0,tool='pencil',drawing=false,last=null,undo=[],redo=[],timer=null,playing=false;
const blank=()=>document.createElement('canvas');function fresh(){const c=blank();c.width=W;c.height=H;return c}function copy(c){const n=fresh();n.getContext('2d').drawImage(c,0,0);return n}function data(c){return c.toDataURL('image/png')}function fromData(src){return new Promise((ok,no)=>{const im=new Image();im.onload=()=>{const c=fresh();c.getContext('2d').drawImage(im,0,0);ok(c)};im.onerror=no;im.src=src})}
function setStatus(s){$('status').textContent=s}function save(){try{localStorage.setItem(KEY,JSON.stringify({name:$('projectName').value,fps:+$('fps').value,frames:frames.map(data)}));setStatus('Saved')}catch(e){setStatus('Save failed')}}function queueSave(){clearTimeout(timer);timer=setTimeout(save,250)}
function render(){ctx.clearRect(0,0,W,H);ctx.drawImage(frames[current],0,0);ox.clearRect(0,0,W,H);if($('onionToggle').checked&&current>0){ox.globalAlpha=.18;ox.drawImage(frames[current-1],0,0);ox.globalAlpha=1}$('frameLabel').textContent=`Frame ${current+1} / ${frames.length}`;$('prev').disabled=current===0;$('next').disabled=current===frames.length-1;$('deleteFrame').disabled=frames.length===1;renderStrip()}
function renderStrip(){const host=$('frames');host.textContent='';frames.forEach((f,i)=>{const b=document.createElement('button');b.className='frame'+(i===current?' active':'');const pic=document.createElement('canvas');pic.width=120;pic.height=90;pic.getContext('2d').drawImage(f,0,0,120,90);const s=document.createElement('span');s.textContent=`Frame ${i+1}`;b.append(pic,s);b.onclick=()=>{commit();current=i;undo=[];redo=[];render()};host.append(b)})}
function commit(){frames[current].getContext('2d').clearRect(0,0,W,H);frames[current].getContext('2d').drawImage(canvas,0,0)}function snapshot(){undo.push(data(canvas));if(undo.length>30)undo.shift();redo=[]}function restore(src){fromData(src).then(c=>{frames[current]=c;render();queueSave()})}
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}
canvas.onpointerdown=e=>{if(playing)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);snapshot();drawing=true;last=point(e)};canvas.onpointermove=e=>{if(!drawing)return;const p=point(e),size=+$('size').value,alpha=+$('opacity').value/100;ctx.save();ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=tool==='marker'?size*2:size;ctx.globalAlpha=tool==='marker'?alpha*.35:alpha;ctx.globalCompositeOperation=tool==='eraser'?'destination-out':'source-over';ctx.strokeStyle=selectedColor;ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.restore();last=p};canvas.onpointerup=canvas.onpointercancel=()=>{if(!drawing)return;drawing=false;commit();renderStrip();queueSave()};
let selectedColor='#30104d';
function selectDefaultColor(value){selectedColor=value;document.querySelectorAll('.colorSwatch').forEach(b=>b.classList.toggle('active',b.dataset.color.toLowerCase()===value.toLowerCase()))}
document.querySelectorAll('.colorSwatch').forEach(b=>b.onclick=()=>selectDefaultColor(b.dataset.color));
document.querySelectorAll('.tool').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;document.querySelectorAll('.tool').forEach(x=>x.classList.toggle('active',x===b))});$('size').oninput=()=>$('sizeOut').value=$('size').value;$('opacity').oninput=()=>$('opacityOut').value=$('opacity').value+'%';$('undo').onclick=()=>{if(!undo.length)return;redo.push(data(canvas));restore(undo.pop())};$('redo').onclick=()=>{if(!redo.length)return;undo.push(data(canvas));restore(redo.pop())};$('clear').onclick=()=>{snapshot();ctx.clearRect(0,0,W,H);commit();render();queueSave()};$('fill').onclick=()=>{snapshot();ctx.save();ctx.globalCompositeOperation='destination-over';ctx.fillStyle=selectedColor;ctx.fillRect(0,0,W,H);ctx.restore();commit();render();queueSave()};
$('add').onclick=()=>{commit();frames.splice(current+1,0,fresh());current++;undo=[];redo=[];render();queueSave()};$('duplicate').onclick=()=>{commit();frames.splice(current+1,0,copy(frames[current]));current++;render();queueSave()};$('deleteFrame').onclick=()=>{if(frames.length<2)return;frames.splice(current,1);current=Math.min(current,frames.length-1);render();queueSave()};$('prev').onclick=()=>{if(current){commit();current--;render()}};$('next').onclick=()=>{if(current<frames.length-1){commit();current++;render()}};$('onionToggle').onchange=render;
$('play').onclick=()=>{if(playing)return;commit();playing=true;let i=0;const step=()=>{if(!playing)return;ctx.clearRect(0,0,W,H);ctx.drawImage(frames[i],0,0);$('frameLabel').textContent=`Playing ${i+1} / ${frames.length}`;i=(i+1)%frames.length;timer=setTimeout(step,1000/Math.max(1,+$('fps').value||6))};step()};$('stop').onclick=()=>{playing=false;clearTimeout(timer);render()};
$('theme').onchange=()=>{document.documentElement.dataset.theme=$('theme').value;localStorage.setItem(THEME,$('theme').value)};$('projectName').oninput=queueSave;$('fps').onchange=queueSave;$('save').onclick=save;$('newProject').onclick=()=>{if(!confirm('Start a new project?'))return;frames=[fresh()];current=0;undo=[];redo=[];$('projectName').value='Untitled Animation';render();save()};
$('exportProject').onclick=()=>{commit();const blob=new Blob([JSON.stringify({app:'FrameForge On the GO',version:2,name:$('projectName').value,fps:+$('fps').value,frames:frames.map(data)})],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=($('projectName').value||'frameforge')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};$('importProject').onclick=()=>$('importInput').click();$('importInput').onchange=async e=>{try{const p=JSON.parse(await e.target.files[0].text());if(!Array.isArray(p.frames)||!p.frames.length)throw Error();frames=await Promise.all(p.frames.map(fromData));current=0;$('projectName').value=p.name||'Imported Animation';$('fps').value=p.fps||6;render();save()}catch{alert('That project file could not be loaded.')}e.target.value=''};
async function init(){const theme=localStorage.getItem(THEME)||'dark';$('theme').value=theme;document.documentElement.dataset.theme=theme;try{const p=JSON.parse(localStorage.getItem(KEY)||'null');if(p&&Array.isArray(p.frames)&&p.frames.length){frames=await Promise.all(p.frames.map(fromData));$('projectName').value=p.name||'Untitled Animation';$('fps').value=p.fps||6}else frames=[fresh()]}catch{frames=[fresh()]}render();setStatus('Ready')}init();
})();